// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD80KEGgtA3H3__wvRNoq0nE5VZJ7GeThE',
    appId: '1:1088481550003:web:e31de618ea905766421ac6',
    messagingSenderId: '1088481550003',
    projectId: 'motorbike-crash-theft-detect',
    authDomain: 'motorbike-crash-theft-detect.firebaseapp.com',
    storageBucket: 'motorbike-crash-theft-detect.appspot.com',
    measurementId: 'G-81PJDTWJQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFilb6lt8sOtarPkP7FtvUBvHluAyOtg',
    appId: '1:1088481550003:android:397a657d6224d1f6421ac6',
    messagingSenderId: '1088481550003',
    projectId: 'motorbike-crash-theft-detect',
    storageBucket: 'motorbike-crash-theft-detect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1plCqanOi-lg6rkirf6f_GP4XtzbWw0',
    appId: '1:1088481550003:ios:877c3de06f2ad775421ac6',
    messagingSenderId: '1088481550003',
    projectId: 'motorbike-crash-theft-detect',
    storageBucket: 'motorbike-crash-theft-detect.appspot.com',
    iosBundleId: 'com.example.motorbikeCrashTheftDetectionSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy1plCqanOi-lg6rkirf6f_GP4XtzbWw0',
    appId: '1:1088481550003:ios:6d3eec74921c5d96421ac6',
    messagingSenderId: '1088481550003',
    projectId: 'motorbike-crash-theft-detect',
    storageBucket: 'motorbike-crash-theft-detect.appspot.com',
    iosBundleId: 'com.example.motorbikeCrashTheftDetectionSystem.RunnerTests',
  );
}
